import SeoHead, { SITE_NAME } from "@/components/marketing/SeoHead";
import MarketingLayout from "@/components/marketing/MarketingLayout";
import Breadcrumbs from "@/components/marketing/Breadcrumbs";

export default function Terms() {
  return (
    <>
      <SeoHead
        title="Terms of Use | SOL Prep"
        description="Terms of use for solprep.com and the SOL Prep study assistant."
        path="/terms"
      />
      <MarketingLayout>
        <div className="container mx-auto max-w-2xl px-4 py-16">
          <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Terms", href: "/terms" }]} />
          <h1 className="font-display mt-4 text-3xl font-bold tracking-tight">Terms of Use</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: 2026</p>

          <div className="mt-6 space-y-5 text-muted-foreground [&_h2]:mt-8 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-foreground [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-5">
            <p>
              These terms cover use of solprep.com and the SOL Prep study
              assistant at app.solprep.com (together, "SOL Prep"). SOL Prep
              is in active pre-launch development; these terms will be
              formalized ahead of general availability.
            </p>

            <h2>What SOL Prep is</h2>
            <p>
              SOL Prep is an independent study tool. It references Virginia's
              publicly published Standards of Learning to organize study
              content, but it is not produced, endorsed, or affiliated with
              the Virginia Department of Education or any local school
              division.
            </p>

            <h2>Educational use only</h2>
            <p>
              Content and practice questions generated by SOL Prep are study
              aids, not official test questions, and are not a guarantee of
              any particular test outcome or score.
            </p>

            <h2>Acceptable use</h2>
            <ul>
              <li>Don't attempt to disrupt, scrape at scale, or reverse-engineer the service.</li>
              <li>Don't use SOL Prep to submit or generate unlawful, abusive, or harmful content.</li>
              <li>Content on solprep.com is provided for personal, non-commercial reference use.</li>
            </ul>

            <h2>No warranty</h2>
            <p>
              SOL Prep is provided "as is," without warranty of any kind,
              while the product is under active development. We work to keep
              standards references and study content accurate, but you
              should confirm official testing details (dates, policies, cut
              scores) directly with the Virginia Department of Education or
              your school division.
            </p>

            <h2>Contact</h2>
            <p>
              Questions about these terms:{" "}
              <a href="mailto:hello@solprep.com" className="text-primary underline underline-offset-4">
                hello@solprep.com
              </a>
              .
            </p>
          </div>
        </div>
      </MarketingLayout>
    </>
  );
}
