import React from 'react';

/**
 * PythonVisual renders a static image generated by Matplotlib via E2B.
 * It provides a premium textbook-style frame with a "Python Powered" indicator.
 */
export default function PythonVisual({ chartData, title, code, caption }) {
  // If no chart data, show a placeholder for the dashboard/simulator
  const imageSrc = chartData 
    ? (chartData.startsWith('data:') ? chartData : `data:image/png;base64,${chartData}`)
    : null;

  return (
    <div className="my-10 w-full max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-1000">
      <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-black/5 dark:border-white/10 overflow-hidden shadow-2xl overflow-hidden group">
        
        {/* Header */}
        <div className="px-8 py-4 border-b border-black/5 dark:border-white/5 flex items-center justify-between bg-slate-50/50 dark:bg-slate-950/50">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-amber-400 rounded-lg flex items-center justify-center shadow-lg shadow-amber-400/20">
              <span className="text-white text-[10px] font-black">PY</span>
            </div>
            <div>
              <span className="text-[0.65rem] font-black text-slate-500 uppercase tracking-[0.2em]">Scientific Visualization</span>
              <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200">{title || 'Python Analysis'}</h4>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <span className="px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-500 text-[10px] font-black uppercase tracking-widest">
              Matplotlib Engine
            </span>
          </div>
        </div>

        {/* Chart Stage */}
        <div className="p-4 md:p-8 bg-white dark:bg-slate-900 flex items-center justify-center min-h-[300px]">
          {imageSrc ? (
            <img 
              src={imageSrc} 
              alt={title || "Scientific Chart"}
              className="max-w-full h-auto rounded-xl shadow-sm transition-transform duration-700 group-hover:scale-[1.01]"
            />
          ) : (
            <div className="flex flex-col items-center gap-4 text-slate-400">
              <div className="w-16 h-16 rounded-2xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center animate-pulse">
                <span className="text-2xl">📊</span>
              </div>
              <p className="text-xs font-bold uppercase tracking-widest">Simulation Ready</p>
            </div>
          )}
        </div>

        {/* Footer / Caption */}
        {caption && (
          <div className="px-8 py-5 bg-slate-50/80 dark:bg-slate-950/80 border-t border-black/5 dark:border-white/5">
             <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed italic">
               {caption}
             </p>
          </div>
        )}

        {/* Code Reveal (Optional) */}
        {code && (
          <details className="group/code">
            <summary className="list-none cursor-pointer px-8 py-3 bg-black/5 dark:bg-white/5 text-[10px] font-black text-slate-400 uppercase tracking-widest hover:text-blue-500 transition-colors flex items-center gap-2">
              <span className="group-open/code:rotate-90 transition-transform">▶</span>
              View Source Analysis
            </summary>
            <div className="p-6 bg-[#1e1e1e] font-mono text-xs text-blue-300/80 overflow-x-auto leading-relaxed border-t border-white/5">
              <pre>{code}</pre>
            </div>
          </details>
        )}
      </div>
    </div>
  );
}
