import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';

/**
 * PythonVisual renders a static image generated by Matplotlib via E2B.
 * It provides a premium textbook-style frame with a "Python Powered" indicator.
 * Now includes a skeleton loading state and detailed debug diagnostics on failure.
 */
export default function PythonVisual({ chartData, title, caption, error, logs }) {
  const [isMaximized, setIsMaximized] = useState(false);
  const [showDebug, setShowDebug] = useState(false);
  const isSvg = chartData && (chartData.includes('<svg') || chartData.startsWith('<?xml'));
  
  const imageSrc = !isSvg && chartData 
    ? (chartData.startsWith('data:') ? chartData : `data:image/png;base64,${chartData}`)
    : null;


  if (error) {
    return (
      <div className="my-10 w-full max-w-4xl mx-auto border-2 border-red-500/10 bg-white dark:bg-slate-900 rounded-[2.5rem] shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-500">
        <div className="px-8 py-5 border-b border-red-500/10 bg-red-50/50 dark:bg-red-950/20 flex items-center justify-between">
          <div className="flex items-center gap-3 text-red-600 dark:text-red-400">
             <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
             <h4 className="font-black uppercase tracking-[0.15em] text-xs">Visual Engine Error</h4>
          </div>
          <button 
            onClick={() => setShowDebug(!showDebug)}
            className="px-4 py-1.5 rounded-full bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 text-[0.6rem] font-black uppercase tracking-widest hover:scale-105 active:scale-95 transition-all"
          >
            {showDebug ? "Hide Diagnostics" : "View Debug Info"}
          </button>
        </div>
        
        <div className="p-8">
          <div className="flex flex-col items-center text-center gap-4 py-6">
            <div className="w-20 h-20 rounded-[2rem] bg-red-50 dark:bg-red-900/10 flex items-center justify-center text-red-500">
               <svg viewBox="0 0 24 24" width="32" height="32" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
            </div>
            <div className="max-w-md">
              <h5 className="text-lg font-bold text-slate-800 dark:text-slate-200 mb-2">Failed to render scientific visual</h5>
              <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed font-medium">
                The Python sandbox encountered an issue while generating this plot. This usually happens due to a mathematical edge case or a timeout.
              </p>
            </div>
          </div>

          {showDebug && (
            <div className="mt-4 animate-in slide-in-from-top-4 duration-500">
              <div className="bg-slate-950 rounded-2xl p-6 overflow-hidden border border-white/5 shadow-inner">
                <div className="flex items-center justify-between mb-4">
                  <span className="text-[0.6rem] font-black text-slate-500 uppercase tracking-widest">E2B Sandbox Traceback</span>
                  <span className="text-[0.55rem] font-mono text-blue-500">exit_code: 1</span>
                </div>
                <div className="max-h-[300px] overflow-y-auto custom-scrollbar">
                  <pre className="text-[0.7rem] leading-relaxed text-blue-400 font-mono whitespace-pre-wrap">
                    {error}
                    {"\n\n" + (logs && logs.length > 0 ? logs.map(l => l.stdout || l.stderr).join('\n') : "No standard output captured.")}
                  </pre>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }

  const RenderChart = ({ className = "" }) => (
    <>
      {isSvg ? (
        <div 
          className={`w-full h-auto flex justify-center py-4 [&>svg]:max-w-full [&>svg]:h-auto [&>svg]:mx-auto ${className}`}
          dangerouslySetInnerHTML={{ __html: chartData }} 
        />
      ) : imageSrc ? (
        <img 
          src={imageSrc} 
          alt={title || "Chart"}
          className={`max-w-full h-auto rounded-xl shadow-sm transition-transform duration-700 ${className}`}
        />
      ) : (
        <div className="flex flex-col items-center gap-4 py-12">
          <svg className="animate-spin h-8 w-8 text-blue-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-20" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-80" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <span className="text-[0.6rem] font-bold uppercase tracking-[0.2em] text-slate-400">Rendering visual...</span>
        </div>
      )}
    </>
  );

  return (
    <>
      <div className="my-10 w-full max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-1000">
        <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-black/5 dark:border-white/10 shadow-2xl overflow-hidden group">
          
          {/* Header */}
          {(title || chartData) && (
            <div className="px-8 py-5 border-b border-black/5 dark:border-white/5 flex items-center justify-between bg-slate-50/50 dark:bg-slate-950/50">
              <h4 className="text-[1.1rem] font-bold text-slate-800 dark:text-slate-200">
                {title ? (
                  <ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>{title}</ReactMarkdown>
                ) : chartData ? (
                  "Scientific Visualization"
                ) : (
                  "Preparing Visualization..."
                )}
              </h4>
              
              {chartData && (
                <button 
                  onClick={() => setIsMaximized(true)}
                  className="p-2.5 rounded-xl bg-slate-200/50 dark:bg-slate-800/50 text-slate-500 hover:text-blue-600 dark:hover:text-blue-400 transition-all hover:scale-110 active:scale-95"
                  title="Maximize"
                >
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"/></svg>
                </button>
              )}
            </div>
          )}

          {/* Chart Stage */}
          <div className={`p-4 md:p-8 bg-white dark:bg-slate-900 flex items-center justify-center ${!chartData ? 'min-h-[400px]' : 'min-h-[300px]'}`}>
            <RenderChart className="group-hover:scale-[1.01]" />
          </div>

          {/* Footer / Caption */}
          {caption && chartData && (
            <div className="px-8 py-6 bg-slate-50/80 dark:bg-slate-950/80 border-t border-black/5 dark:border-white/5">
               <div className="text-[0.95rem] font-medium text-slate-600 dark:text-slate-400 leading-relaxed">
                 <ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>{caption}</ReactMarkdown>
               </div>
            </div>
          )}
        </div>
      </div>

      {/* Fullscreen Overlay */}
      {isMaximized && (
        <div className="fixed inset-0 z-[9999] bg-white/95 dark:bg-slate-950/95 backdrop-blur-2xl flex flex-col p-6 md:p-12 animate-in fade-in zoom-in-95 duration-300">
          <div className="max-w-6xl mx-auto w-full h-full flex flex-col">
            <div className="flex items-center justify-between mb-8">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center text-white shadow-lg shadow-blue-600/20">
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M3 3v18h18"/><path d="m19 9-5 5-4-4-3 3"/></svg>
                </div>
                <h2 className="text-2xl font-black tracking-tight text-slate-900 dark:text-white">
                  {title ? (
                    <ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>{title}</ReactMarkdown>
                  ) : (
                    "Visualization Detail"
                  )}
                </h2>
              </div>
              <button 
                onClick={() => setIsMaximized(false)}
                className="p-4 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-500 hover:text-slate-900 dark:hover:text-white transition-all hover:rotate-90 active:scale-95 shadow-sm"
              >
                <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>
              </button>
            </div>

            <div className="flex-1 flex items-center justify-center overflow-hidden bg-slate-50 dark:bg-slate-900/50 rounded-[3rem] border border-black/5 dark:border-white/5 p-4 md:p-12 shadow-inner">
              <RenderChart className="max-h-full w-auto" />
            </div>

            {caption && (
              <div className="mt-8 max-w-3xl mx-auto w-full text-center">
                <div className="text-[1.1rem] font-medium text-slate-600 dark:text-slate-400 leading-relaxed italic">
                  <ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>{caption}</ReactMarkdown>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}

