/**
 * Compiles a sequence of json-render patches into a single Spec object.
 * 
 * Supports 'add' operations commonly generated by the AI for root, elements, and state.
 */
export function compilePatchesToSpec(patchLines) {
  const spec = {
    root: "",
    elements: {},
    state: {}
  };

  patchLines.forEach(line => {
    if (!line || typeof line !== 'string' || !line.trim()) return;

    try {
      const patch = JSON.parse(line.trim());
      if (patch.op === 'add') {
        const path = patch.path;
        const value = patch.value;

        if (path === '/root') {
          spec.root = value;
        } else if (path.startsWith('/elements/')) {
          const key = path.replace('/elements/', '');
          spec.elements[key] = value;
        } else if (path.startsWith('/state/')) {
          const key = path.replace('/state/', '');
          spec.state[key] = value;
        }
      }
    } catch (e) {
      // Ignore invalid JSON lines (might be partial during streaming)
      console.warn("Failed to parse patch line:", line, e);
    }
  });

  return spec;
}

/**
 * Detects if a string contains JSONL patches.
 */
export function isJSONLPatch(text) {
  const trimmed = text.trim();
  return trimmed.startsWith('{"op":') || trimmed.includes('\n{"op":');
}
